### ISSUE TITLE
[compare.py] NaN == NaN

### ISSUE THREAD

**Issue by chovyy** [eth-cscs/serialbox2#148]
@vectorflux wrote here: [Pull Request #144](https://github.com/eth-cscs/serialbox2/pull/144#issuecomment-381899535):

> One comment which probably does not fit here: compare.py always flags differences between NaNs. Since our arrays frequently contain halo regions which are not defined, it would be more convenient if NaN was considered equal to NaN. Is this a reasonable thing, or does that open a can of worms in other places?

**Comment by havogt** [comment]
I would suggest to add a command line option to disable checking for nans. Feel free to provide a PR with this change.

**Comment by chovyy** [comment]
My hints for that:

`NaN == NaN` is always false, so if you just compare two values `a == b` and both are NaN they will appear to be unequal. If you want to catch that special case you can't write something like `if a == NaN` because that will also be always false, but what you can do is to write `if (a != a)` to find out whether a is NaN. So, `a == b` becomes `a == b && a != a ^ b != b`.

**Comment by chovyy** [comment]
@havogt:
> I would suggest to add a command line option to disable checking for nans.

What do think should be the default behaviour? The way it is or as requested by @vectorflux. I would think that two NaNs shall pass as equal by default.

**Comment by havogt** [comment]
@clementval @lxavier Who are the main users of the tool? What are our defaults here?

**Comment by clementval** [comment]
The tool is not so good anyway and would need major refactoring because it's super slow with big data sets ... but I would say that if the same points have both NaNs it should not trigger a difference by default.

**Comment by lxavier** [comment]
I agree with with @clementval (only if both NaN)
