### ISSUE TITLE
Serialbox version information in metadata is automatically updated

### ISSUE THREAD

**Issue by stefanmoosbrugger** [eth-cscs/serialbox2#151]
It seems that serialbox (version 2.3.1) is automatically updating the version number of metadata files (and rendering them unusable in some cases). This is super annoying if the user wants to reuse the files with an older version of serialbox (e.g., 2.3.0). Serialbox asserts when the library version information does not match. 

In my scenario I was using the compare tool of version 2.3.1 that messed up my metadata files.

**Comment by clementval** [comment]
@stefanmoosbrugger And I think "patch" version should not change the metadata files ... I'm assuming `2.3.1` should be compatible to `2.3.0`
