### ISSUE TITLE
std::filesystem check in CMakeLists.txt uses hard coded library paths

### ISSUE THREAD

**Issue by phmarti** [eth-cscs/serialbox2#160]
The check for the experimental std::filesystem support is based on hard coded GCC paths which are dependent on distribution/install.

For example, the check breaks for the Gentoo Linux distribution, where the path contains the full version string in order to work with multiple version of GCC.

Can we replace this with something more flexible?

**Comment by clementval** [comment]
@phmarti I would propose to implement the few features we need directly in the lib and also get rid of the boost dependency as well.

**Comment by phmarti** [comment]
@clementval It isn't about new features, the problem is the CMake check itself. If fails because of the hardcoded paths and as a result brings in a dependency on Boost. experimental/filesystem is available but it fails to find it because it looks in the wrong place. 

Removing boost would of course solve the issue, but doesn't that break some of the older supported compilers?

**Comment by clementval** [comment]
@phmarti Yeah I know this but as this is an experimental filesystem, it is also not really reliable. As we use only two-three features from there, it should be easy to have a compiler/library agnostic implementation of these.

**Comment by havogt** [comment]
Fixed in #169
