### ISSUE TITLE
compare.py overwrites MetaData JSON files

### ISSUE THREAD

**Issue by phmarti** [eth-cscs/serialbox2#194]
Assuming the reference serialization data is generated with a certain version (say v2.4.2). Using compare.py from say v2.5.1 will overwrite the MetaData JSON files with a new version.

It is then impossible to reuse the serialization data with the original binary (using version v2.4.2) as reading the serialization data fails due to version mismatch between MetaData and library.

I don't see any reason why a comparison tool should overwrite any of the data.

**Comment by havogt** [comment]
Interesting...

**Comment by havogt** [comment]
Does it "update" the version numbers in both json files?

**Comment by phmarti** [comment]
Yes, both JSON files get "updated" to the new version.

**Comment by phmarti** [comment]
And using v2.5.2 on daint, updates the version number to 251 ...

Path to used version /project/c14/install/daint/serialbox2_v2.4.2/serialbox2_v2.5.2/gnu/
