### ISSUE TITLE
Backport tools from old serialbox

### ISSUE THREAD

**Issue by clementval** [eth-cscs/serialbox2#30]
Tools from old serialbox are not in the current repository. Would be nice to have at leat the compare tool. 

https://github.com/MeteoSwiss-APN/serialbox/tree/master/tools

**Comment by chovyy** [comment]
Since I have once created these tools, I definitely plan to port them to serialbox2, but I cannot tell how soon this will happen. Btw, the latest version can be found here:  https://github.com/fortesg/serialbox-compare

**Comment by clementval** [comment]
Ok! No problem. If I have some times, I'll maybe to some stuff as well!

**Comment by chovyy** [comment]
Cool. :-)

**Comment by havogt** [comment]
@thfabian Will port the tools to python

**Comment by havogt** [comment]
replaced by a python compare tool
