### ISSUE TITLE
Why does serialbox2 uses two distinct metadata JSON files?

### ISSUE THREAD

**Issue by adamryczkowski** [eth-cscs/serialbox2#61]
I am curious, why did you introduce another metadatafile with Serialbox2? The JSON already handles structured data, so you could simply store the additional metadata inside the original JSON file (the one without the `Metadata-` prefix).

**Comment by thfabian** [comment]
This was done to easily convert your data from one archive to another (e.g Binary to NetCDF). All archive specific meta-data are stored in the `ArchiveMetaData-*.json` while the archive independent meta-data (like the Savepoints etc.) are stored in the normal `MetaData-field.json`.

**Comment by havogt** [comment]
Thanks @thfabian
