### ISSUE TITLE
Does serialbox2 supports serializing field into more than one format?

### ISSUE THREAD

**Issue by adamryczkowski** [eth-cscs/serialbox2#64]
(Continuation of the closed topic https://github.com/eth-cscs/serialbox2/issues/61#event-1335639038)

>This was done to easily convert your data from one archive to another (e.g Binary to NetCDF). All archive specific meta-data are stored in the ArchiveMetaData-*.json while the archive independent meta-data (like the Savepoints etc.) are stored in the normal MetaData-field.json.

It suggests you are preparing to support saving in hetergenous formats, e.g. one field in binary format, and another in NetCDF. Am I right? Is it already supported? We do use Serialbox to serialize into two formats, but we solve it on the level of CMake and conditional compilation.

**Comment by thfabian** [comment]
It wasn’t siggesting this and I also dont see much benefit in doing so. I would suggest to only write serialbox2 archives (you can still read serialbox1 archives without modifications). But to answer your question no this is not supported and Im not aware of any efforts in that direction.

**Comment by havogt** [comment]
I think we don't need this functionality.
